#ifndef GW_ERRORS_H_
#define GW_ERRORS_H_

/* Errors */
#define GW_ERROR_DUPLICATED_SCRIPT_HASH 40
#define GW_ERROR_RECOVER 41
#define GW_ERROR_NOT_FOUND 42
#define GW_ERROR_INVALID_DATA 43
#define GW_ERROR_BUFFER_OVERFLOW 44
#define GW_ERROR_INVALID_CONTEXT 45
#define GW_ERROR_DYNAMIC_LINKING 46
#define GW_ERROR_MISMATCH_CHANGE_SET 47
#define GW_ERROR_MISMATCH_RETURN_DATA 48
#define GW_ERROR_UNKNOWN_ARGS 49
#define GW_ERROR_UNKNOWN_SCRIPT_CODE_HASH 50
#define GW_ERROR_ACCOUNT_NOT_FOUND 51
#define GW_ERROR_DATA_CELL_NOT_FOUND 52
#define GW_ERROR_INVALID_CONTRACT_SCRIPT 53
#define GW_ERROR_INVALID_SUDT_SCRIPT 54

/* Merkle Errors*/
#define GW_ERROR_INVALID_PROOF_LENGTH 60
#define GW_ERROR_INVALID_PROOF 61
#define GW_ERROR_INVALID_STACK 62
#define GW_ERROR_INVALID_SIBLING 63

#endif
