#ifndef GW_ERRORS_H_
#define GW_ERRORS_H_

/* Godwoken System Fatal Errors
   Shouldn't be recovered by user programs.
 */

/* Data Fatals */
#define GW_FATAL_BUFFER_OVERFLOW 100
#define GW_FATAL_INVALID_CONTEXT 101
#define GW_FATAL_INVALID_DATA 102
#define GW_FATAL_MISMATCH_RETURN_DATA 103
#define GW_FATAL_UNKNOWN_ARGS 104
#define GW_FATAL_INVALID_SUDT_SCRIPT 105

/* Notfound Fatals */
#define GW_FATAL_DATA_CELL_NOT_FOUND 110
#define GW_FATAL_STATE_KEY_NOT_FOUND 111
#define GW_FATAL_SIGNATURE_CELL_NOT_FOUND 112
#define GW_FATAL_ACCOUNT_NOT_FOUND 113

/* Merkle Fatals */
#define GW_FATAL_INVALID_PROOF 120
#define GW_FATAL_INVALID_STACK 121
#define GW_FATAL_INVALID_SIBLING 122

/* User Errors */
#define GW_ERROR_DUPLICATED_SCRIPT_HASH 200
#define GW_ERROR_UNKNOWN_SCRIPT_CODE_HASH 201
#define GW_ERROR_INVALID_CONTRACT_SCRIPT 202
#define GW_ERROR_NOT_FOUND 203
#define GW_ERROR_RECOVER 204

#endif
